Name: task-LO
Summary: Task for Office Suite (core)
Version: 4.3
Release: 2
License: LGPLv3
URL: http://www.libreoffice.org/
Group: Tasks
BuildArch: noarch

Requires: libreoffice4.3-freedesktop-menus
Requires: libobasis4.3-base
Requires: libobasis4.3-calc
Requires: libobasis4.3-core01
Requires: libobasis4.3-core02
Requires: libobasis4.3-core03
Requires: libobasis4.3-core04
Requires: libobasis4.3-core05
Requires: libobasis4.3-core06
Requires: libobasis4.3-core07
Requires: libobasis4.3-draw
Requires: libobasis4.3-en-US-base
Requires: libobasis4.3-en-US-calc
Requires: libobasis4.3-en-US-math
Requires: libobasis4.3-en-US-res
Requires: libobasis4.3-en-US-writer
Requires: libobasis4.3-en-US
Requires: libobasis4.3-extension-beanshell-script-provider
Requires: libobasis4.3-extension-javascript-script-provider
Requires: libobasis4.3-extension-mediawiki-publisher
Requires: libobasis4.3-extension-nlpsolver
Requires: libobasis4.3-extension-report-builder
Requires: libobasis4.3-gnome-integration
Requires: libobasis4.3-graphicfilter
Requires: libobasis4.3-images
Requires: libobasis4.3-impress
Requires: libobasis4.3-kde-integration
Requires: libobasis4.3-math
Requires: libobasis4.3-ogltrans
Requires: libobasis4.3-onlineupdate
Requires: libobasis4.3-ooofonts
Requires: libobasis4.3-ooolinguistic
Requires: libobasis4.3-postgresql-sdbc
Requires: libobasis4.3-pyuno
Requires: libobasis4.3-writer
Requires: libobasis4.3-xsltfilter
Requires: libreoffice4.3-base
Requires: libreoffice4.3-calc
Requires: libreoffice4.3-dict-en
Requires: libreoffice4.3-dict-es
Requires: libreoffice4.3-dict-fr
Requires: libreoffice4.3-draw
Requires: libreoffice4.3-en-US
Requires: libreoffice4.3-impress
Requires: libreoffice4.3-math
Requires: libreoffice4.3-ure
Requires: libreoffice4.3-writer
Requires: libreoffice4.3


Obsoletes: libreoffice4.2-freedesktop-menus
Obsoletes: libobasis4.2-base
Obsoletes: libobasis4.2-calc
Obsoletes: libobasis4.2-core01
Obsoletes: libobasis4.2-core02
Obsoletes: libobasis4.2-core03
Obsoletes: libobasis4.2-core04
Obsoletes: libobasis4.2-core05
Obsoletes: libobasis4.2-core06
Obsoletes: libobasis4.2-core07
Obsoletes: libobasis4.2-draw
Obsoletes: libobasis4.2-en-US-base
Obsoletes: libobasis4.2-en-US-calc
Obsoletes: libobasis4.2-en-US-math
Obsoletes: libobasis4.2-en-US-res
Obsoletes: libobasis4.2-en-US-writer
Obsoletes: libobasis4.2-en-US
Obsoletes: libobasis4.2-extension-beanshell-script-provider
Obsoletes: libobasis4.2-extension-javascript-script-provider
Obsoletes: libobasis4.2-extension-mediawiki-publisher
Obsoletes: libobasis4.2-extension-nlpsolver
Obsoletes: libobasis4.2-extension-report-builder
Obsoletes: libobasis4.2-gnome-integration
Obsoletes: libobasis4.2-graphicfilter
Obsoletes: libobasis4.2-images
Obsoletes: libobasis4.2-impress
Obsoletes: libobasis4.2-kde-integration
Obsoletes: libobasis4.2-math
Obsoletes: libobasis4.2-ogltrans
Obsoletes: libobasis4.2-onlineupdate
Obsoletes: libobasis4.2-ooofonts
Obsoletes: libobasis4.2-ooolinguistic
Obsoletes: libobasis4.2-postgresql-sdbc
Obsoletes: libobasis4.2-pyuno
Obsoletes: libobasis4.2-writer
Obsoletes: libobasis4.2-xsltfilter
Obsoletes: libreoffice4.2-base
Obsoletes: libreoffice4.2-calc
Obsoletes: libreoffice4.2-dict-en
Obsoletes: libreoffice4.2-dict-es
Obsoletes: libreoffice4.2-dict-fr
Obsoletes: libreoffice4.2-draw
Obsoletes: libreoffice4.2-en-US
Obsoletes: libreoffice4.2-impress
Obsoletes: libreoffice4.2-math
Obsoletes: libreoffice4.2-ure
Obsoletes: libreoffice4.2-writer
Obsoletes: libreoffice4.2

Requires: task-java

Obsoletes: libreoffice4.1-freedesktop-menus
Obsoletes: libobasis4.1-base
Obsoletes: libobasis4.1-calc
Obsoletes: libobasis4.1-core01
Obsoletes: libobasis4.1-core02
Obsoletes: libobasis4.1-core03
Obsoletes: libobasis4.1-core04
Obsoletes: libobasis4.1-core05
Obsoletes: libobasis4.1-core06
Obsoletes: libobasis4.1-core07
Obsoletes: libobasis4.1-draw
Obsoletes: libobasis4.1-en-US-base
Obsoletes: libobasis4.1-en-US-calc
Obsoletes: libobasis4.1-en-US-math
Obsoletes: libobasis4.1-en-US-res
Obsoletes: libobasis4.1-en-US-writer
Obsoletes: libobasis4.1-en-US
Obsoletes: libobasis4.1-extension-beanshell-script-provider
Obsoletes: libobasis4.1-extension-javascript-script-provider
Obsoletes: libobasis4.1-extension-mediawiki-publisher
Obsoletes: libobasis4.1-extension-nlpsolver
Obsoletes: libobasis4.1-extension-presentation-minimizer
Obsoletes: libobasis4.1-extension-report-builder
Obsoletes: libobasis4.1-gnome-integration
Obsoletes: libobasis4.1-graphicfilter
Obsoletes: libobasis4.1-images
Obsoletes: libobasis4.1-impress
Obsoletes: libobasis4.1-kde-integration
Obsoletes: libobasis4.1-math
Obsoletes: libobasis4.1-ogltrans
Obsoletes: libobasis4.1-onlineupdate
Obsoletes: libobasis4.1-ooofonts
Obsoletes: libobasis4.1-ooolinguistic
Obsoletes: libobasis4.1-postgresql-sdbc
Obsoletes: libobasis4.1-pyuno
Obsoletes: libobasis4.1-writer
Obsoletes: libobasis4.1-xsltfilter
Obsoletes: libreoffice4.1-base
Obsoletes: libreoffice4.1-calc
Obsoletes: libreoffice4.1-dict-en
Obsoletes: libreoffice4.1-dict-es
Obsoletes: libreoffice4.1-dict-fr
Obsoletes: libreoffice4.1-draw
Obsoletes: libreoffice4.1-en-US
Obsoletes: libreoffice4.1-impress
Obsoletes: libreoffice4.1-math
Obsoletes: libreoffice4.1-ure
Obsoletes: libreoffice4.1-writer
Obsoletes: libreoffice4.1

Obsoletes: libobasis4.0-base
Obsoletes: libobasis4.0-calc
Obsoletes: libobasis4.0-core01
Obsoletes: libobasis4.0-core02
Obsoletes: libobasis4.0-core03
Obsoletes: libobasis4.0-core04
Obsoletes: libobasis4.0-core05
Obsoletes: libobasis4.0-core06
Obsoletes: libobasis4.0-core07
Obsoletes: libobasis4.0-draw
Obsoletes: libobasis4.0-en-US-base
Obsoletes: libobasis4.0-en-US-calc
Obsoletes: libobasis4.0-en-US-math
Obsoletes: libobasis4.0-en-US-res
Obsoletes: libobasis4.0-en-US-writer
Obsoletes: libobasis4.0-en-US
Obsoletes: libobasis4.0-extension-beanshell-script-provider
Obsoletes: libobasis4.0-extension-javascript-script-provider
Obsoletes: libobasis4.0-extension-mediawiki-publisher
Obsoletes: libobasis4.0-extension-nlpsolver
Obsoletes: libobasis4.0-extension-presentation-minimizer
Obsoletes: libobasis4.0-extension-report-builder
Obsoletes: libobasis4.0-gnome-integration
Obsoletes: libobasis4.0-graphicfilter
Obsoletes: libobasis4.0-images
Obsoletes: libobasis4.0-impress
Obsoletes: libobasis4.0-kde-integration
Obsoletes: libobasis4.0-math
Obsoletes: libobasis4.0-ogltrans
Obsoletes: libobasis4.0-onlineupdate
Obsoletes: libobasis4.0-ooofonts
Obsoletes: libobasis4.0-ooolinguistic
Obsoletes: libobasis4.0-postgresql-sdbc
Obsoletes: libobasis4.0-pyuno
Obsoletes: libobasis4.0-writer
Obsoletes: libobasis4.0-xsltfilter
Obsoletes: libreoffice4.0-base
Obsoletes: libreoffice4.0-calc
Obsoletes: libreoffice4.0-dict-en
Obsoletes: libreoffice4.0-dict-es
Obsoletes: libreoffice4.0-dict-fr
Obsoletes: libreoffice4.0-draw
Obsoletes: libreoffice4.0-en-US
Obsoletes: libreoffice4.0-impress
Obsoletes: libreoffice4.0-math
Obsoletes: libreoffice4.0-ure
Obsoletes: libreoffice4.0-writer
Obsoletes: libreoffice4.0


Conflicts: lomanager

Obsoletes: libobasis3.6-base
Obsoletes: libobasis3.6-binfilter
Obsoletes: libobasis3.6-calc
Obsoletes: libobasis3.6-core01
Obsoletes: libobasis3.6-core02
Obsoletes: libobasis3.6-core03
Obsoletes: libobasis3.6-core04
Obsoletes: libobasis3.6-core05
Obsoletes: libobasis3.6-core06
Obsoletes: libobasis3.6-core07
Obsoletes: libobasis3.6-draw
Obsoletes: libobasis3.6-en-US-base
Obsoletes: libobasis3.6-en-US-calc
Obsoletes: libobasis3.6-en-US-math
Obsoletes: libobasis3.6-en-US-res
Obsoletes: libobasis3.6-en-US-writer
Obsoletes: libobasis3.6-en-US
Obsoletes: libobasis3.6-extension-beanshell-script-provider
Obsoletes: libobasis3.6-extension-javascript-script-provider
Obsoletes: libobasis3.6-extension-mediawiki-publisher
Obsoletes: libobasis3.6-extension-nlpsolver
Obsoletes: libobasis3.6-extension-pdf-import
Obsoletes: libobasis3.6-extension-presentation-minimizer
Obsoletes: libobasis3.6-extension-presenter-screen
Obsoletes: libobasis3.6-extension-python-script-provider
Obsoletes: libobasis3.6-extension-report-builder
Obsoletes: libobasis3.6-gnome-integration
Obsoletes: libobasis3.6-graphicfilter
Obsoletes: libobasis3.6-images
Obsoletes: libobasis3.6-impress
Obsoletes: libobasis3.6-javafilter
Obsoletes: libobasis3.6-kde-integration
Obsoletes: libobasis3.6-math
Obsoletes: libobasis3.6-ogltrans
Obsoletes: libobasis3.6-onlineupdate
Obsoletes: libobasis3.6-ooofonts
Obsoletes: libobasis3.6-ooolinguistic
Obsoletes: libobasis3.6-postgresql-sdbc
Obsoletes: libobasis3.6-pyuno
Obsoletes: libobasis3.6-writer
Obsoletes: libobasis3.6-xsltfilter
Obsoletes: libreoffice3.6-base
Obsoletes: libreoffice3.6-calc
Obsoletes: libreoffice3.6-dict-en
Obsoletes: libreoffice3.6-dict-es
Obsoletes: libreoffice3.6-dict-fr
Obsoletes: libreoffice3.6-draw
Obsoletes: libreoffice3.6-en-US
Obsoletes: libreoffice3.6-impress
Obsoletes: libreoffice3.6-math
Obsoletes: libreoffice3.6-stdlibs
Obsoletes: libreoffice3.6-ure
Obsoletes: libreoffice3.6-writer
Obsoletes: libreoffice3.6
Obsoletes: libreoffice3.6-mandriva-menus

Obsoletes: libobasis3.5-base
Obsoletes: libobasis3.5-binfilter
Obsoletes: libobasis3.5-calc
Obsoletes: libobasis3.5-core01
Obsoletes: libobasis3.5-core02
Obsoletes: libobasis3.5-core03
Obsoletes: libobasis3.5-core04
Obsoletes: libobasis3.5-core05
Obsoletes: libobasis3.5-core06
Obsoletes: libobasis3.5-core07
Obsoletes: libobasis3.5-draw
Obsoletes: libobasis3.5-en-US-base
Obsoletes: libobasis3.5-en-US-calc
Obsoletes: libobasis3.5-en-US-math
Obsoletes: libobasis3.5-en-US-res
Obsoletes: libobasis3.5-en-US-writer
Obsoletes: libobasis3.5-en-US
Obsoletes: libobasis3.5-extension-beanshell-script-provider
Obsoletes: libobasis3.5-extension-javascript-script-provider
Obsoletes: libobasis3.5-extension-mediawiki-publisher
Obsoletes: libobasis3.5-extension-nlpsolver
Obsoletes: libobasis3.5-extension-pdf-import
Obsoletes: libobasis3.5-extension-presentation-minimizer
Obsoletes: libobasis3.5-extension-presenter-screen
Obsoletes: libobasis3.5-extension-python-script-provider
Obsoletes: libobasis3.5-extension-report-builder
Obsoletes: libobasis3.5-gnome-integration
Obsoletes: libobasis3.5-graphicfilter
Obsoletes: libobasis3.5-images
Obsoletes: libobasis3.5-impress
Obsoletes: libobasis3.5-javafilter
Obsoletes: libobasis3.5-kde-integration
Obsoletes: libobasis3.5-math
Obsoletes: libobasis3.5-ogltrans
Obsoletes: libobasis3.5-onlineupdate
Obsoletes: libobasis3.5-ooofonts
Obsoletes: libobasis3.5-ooolinguistic
Obsoletes: libobasis3.5-postgresql-sdbc
Obsoletes: libobasis3.5-pyuno
Obsoletes: libobasis3.5-writer
Obsoletes: libobasis3.5-xsltfilter
Obsoletes: libreoffice3.5-base
Obsoletes: libreoffice3.5-calc
Obsoletes: libreoffice3.5-dict-en
Obsoletes: libreoffice3.5-dict-es
Obsoletes: libreoffice3.5-dict-fr
Obsoletes: libreoffice3.5-draw
Obsoletes: libreoffice3.5-en-US
Obsoletes: libreoffice3.5-impress
Obsoletes: libreoffice3.5-math
Obsoletes: libreoffice3.5-stdlibs
Obsoletes: libreoffice3.5-ure
Obsoletes: libreoffice3.5-writer
Obsoletes: libreoffice3.5
Obsoletes: libreoffice3.5-mandriva-menus

Buildroot: %{_tmppath}/%{name}-%{version}-buildroot
%description
LibreOffice is the power-packed free, libre and open source personal productivity suite for Windows, Macintosh and GNU/Linux, that gives you six feature-rich applications for all your document production and data processing needs: Writer, Calc, Impress, Draw, Math and Base. Support and documentation is free from our large, dedicated community of users, contributors and developers. You, too, can get involved!

%files


%changelog
* Sat Mar 25 2011 Mank <Mank1@seznam.cz> 4.3-1
- initial task packages
